### ISSUE TITLE
'-' in package name

### ISSUE THREAD

**Issue by q-b** [morepath/morepath-cookiecutter#13]
Hi,

My first package was named `morepath-something`, I had to change the `-` to `_` manually, else calling `pip` failed with a cryptic error message.

``` python
console_scripts=[
    'run-app = morepath_something.__main__:run',
                       ^
                      here
],
```

Thank you anyway for the template!

**Comment by taschini** [comment]
@href, AFAICS the easiest way to prevent this kind of problem from arising again is to validate the `package_name` following the [example in the docs](https://cookiecutter.readthedocs.io/en/latest/advanced/hooks.html#example-validating-template-variables).

A more sophisticated solution might be to have two separate variables, say `project_name` and `package_name`, the latter having as default value a regex'ed version of the former to make it Python friendly.

**Comment by faassen** [comment]
+1 on not trying to be smart and just not accept it

**Comment by href** [comment]
Thank you @q-b for reporting this issue. The latest commit has a hook that should warn users early:

https://github.com/morepath/morepath-cookiecutter/commit/6cf48efe59b22aeb5fccfa68010a885a5e13db63

@taschini, thanks - I used the example in slightly modified form (cookiecutter's example doesn't accept packages with a single character and they do not handle namespaces).
