### ISSUE TITLE
instead of a redirect show a link in the root page

### ISSUE THREAD

**Issue by faassen** [morepath/morepath-cookiecutter#5]
I think it would be clearer to show a link (or even multiple links to multiple names) in the root page instead of doing a redirect to 'world' immediately. This way people realize that they can change the path a bit more quickly.

**Comment by faassen** [comment]
And typically in real world applications people won't redirect from root.

**Comment by href** [comment]
Fair point. Root is now a very basic collection. We could of course turn it into a more fleshed-out collection now, but I'm hesitant to go too far with this template. I don't want the end product to be too perfect. That should be up to the users to figure out.

We also generate two separate projects out of one template, so there's a limit to what we can add before it gets too complicated.
