### ISSUE TITLE
env/bin/py.test could not find the tests

### ISSUE THREAD

**Issue by henri-hulski** [morepath/morepath-cookiecutter#8]
After replacing in setup.cfg

```
[pytest]
norecursedirs = env
```

with

```
[pytest]
testpaths = {{cookiecutter.package_name}}
```

everything works fine.

**Comment by href** [comment]
I can't reproduce this problem. Do you have any more information?
Also, your proposal would not work a namespaced package is used.

We'd have to at least use

``` python
testpaths = {{cookiecutter.package_name.split('.')[0]}}
```

**Comment by henri-hulski** [comment]
Actually I tried it again and now it's working.
So I think we should leave it.
When I recover the problem I will reopen.
